### ISSUE TITLE
Employee Accounts

### ISSUE THREAD

**Issue by RyanYoak** [DataByne/uraPointOfSale#18] opened 2019-10-02 18:56 UTC
As a business owner, I want each of my employees to have an account that has fewer privileges than mine so they cannot edit sensitive data and I can keep track of what sales they make and when

**Comment by kyletpugh** [comment] 2019-10-02 19:54
What about the business owner's account?

**Comment by kyletpugh** [comment] 2019-10-13 01:18
Duplicate of #17.

**Closed by kyletpugh** 2019-10-13 01:18 UTC
Labels: user story
