### ISSUE TITLE
Sales Analytics 

### ISSUE THREAD

**Issue by RyanYoak** [DataByne/uraPointOfSale#15] opened 2019-10-02 18:52 UTC
As an owner, I want to know when my sales are the highest, what factors affect sales, and possibly predict what similar weeks or days sales will be based on previous weeks.

**Comment by peterle08** [comment] 2019-10-09 20:28
- Knowing "when my sales are the highest" or the lowest , is it a template of Business Report #22?

- Factors that affect the sales are variable, so I think it's hard to determine

- Periodic Sale revenue is also a template Business Report #22

**Comment by kyletpugh** [comment] 2019-10-13 01:13
I agree, this is a duplicate of #22.

**Closed by kyletpugh** 2019-10-13 01:13 UTC
Labels: duplicate, user story
